### ISSUE TITLE
Location StreamController doesn't fire data

### ISSUE THREAD

**Issue by DIEZC005** [peiffer-innovations/automated_testing_framework_plugin_gps#1]
Hi, I'm trying to listen to `onLocationChanged` stream in `GpsPlugin` class but it never initialize correctly, so, it doesn't add positions when user change location. I've seen that in the `initialize` method, this line never comes true:

`if (_locationSubscription == null && _overriddenLocation == null) `

cause `_locationSubscription` is always != null.

Please can you check it? Or if maybe I'm missing something?. Thanks in advance.

**Comment by jpeiffer** [comment]
So what that code block says (in my best attempt to describe it in English) is...

If there is not already a subscription, and no one has set an override for a test, go ahead and create a subscription.

The `_locationStreamController` is a broadcast stream.  That means any event goes to all listeners.  Once a listener is subscribed, it creates the `_locationSubscription` and doesn't create any more because there's only one GPS so there's not a lot of point.

A broadcast stream will only fire after being listened to when a new event comes in.  This is different than a single stream which will fire all pending events on first (and only allowed) subscription.  So if you subscribed to it after the event has fired, and the device has not moved enough to get subsequent events from the GPS (there's a delta threshold from the underlying `Geolocator` where it won't fire new events if you are still basically in the same spot) then you are correct, you will not receive any events from the stream.

I'm not sure your issue is as you describe.  Rather, I think you are subscribing to the stream after it said "you are here" and your device just never moved from "here".

It seems like you have two viable options...  Either you can subscribe to the scream and then call the `currentLocation` to get the first event, or you can call the `refresh` to force the stream to resubscribe and thus trigger the event.

If neither of those two work for you, please let me know and I will investigate further.

**Comment by DIEZC005** [comment]
Hi, those solutions solve partially the issue. I'm calling `currentLocation` to get the first event, works fine, But `refresh` doesn't works because this depend on if `_overriddenLocation != null` to add new positions and this will be always false due to I need to use the position value from the device.

To test when location change I'm using iOS simulator and setting custom locations, if I suscribe to `Geolocator` directly it works fine. 

In resume, what I see, Is that I will never get a subscription both in `initialize` or `refresh` functions because I'm not overriding the locations, as the code is:

<img width="429" alt="Screen Shot 2021-10-19 at 10 20 04 AM" src="https://user-images.githubusercontent.com/89795794/137941152-e64616c4-5e7a-4c76-8c17-b13a43530677.png">

**Comment by jpeiffer** [comment]
Ah ha.  Yep, I totally inverted that logic.  Should have been `if (_overriddenLocation == null) { ... }`.  Just fixed with a push tonight on v1.0.1.

Let me know if this solves your issue.
